FROM centos:latest
RUN yum install -y epel-release && \
    yum install -y python-pip && \
    pip install "ansible<2.6"

# provision
# COPY . /code/
COPY . /code/roles/test_role
COPY tests/docker.yaml /code/
WORKDIR /code/
RUN ansible-playbook -i roles/test_role/tests/inventory \
    docker.yaml --connection=local -vv

